media:
  input: public/assets
  output: /assets
  categories: [ "image" ]

content:
  - name: homepage
    label: Homepage
    type: file
    path: content/homepage
    fields:
      - { name: title, label: Main Heading, type: string, required: true }
      - { name: description, label: Main Description, type: text }
      - name: featureBoxes
        label: Feature Boxes
        type: object
        fields:
          - { name: title, label: Box Title, type: string }
          - { name: content, label: Box Content, type: text }

  - name: events
    label: Events
    type: collection
    path: content/events
    fields:
      - { name: title, label: Event Title, type: string, required: true }
      - { name: date, label: Event Date, type: date, required: true }
      - { name: time, label: Event Time, type: string }
      - { name: location, label: Location, type: string }
      - { name: description, label: Description, type: rich-text }

  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }